### PR TITLE
Use Github releases

### PR DESCRIPTION
**Pull request by bochecha**
This greatly simplify the management of this website.

Currently done for libcangjie and ibus-cangjie.

### CODE REVIEW

**Comment by bochecha** [comment]
@yookoala Ping?

**Comment by yookoala** [comment]
Whats up?

樹雄

**Comment by bochecha** [comment]
Just wondering if you'd have time to review this pull request, it's been open for a while. :smile:

**Comment by yookoala** [comment]
Oops. I though I've merged this

**Pull request merged**
